KERNEL_VERSION_SANITY_SKIP = "1"

# Intel lts v6.12
KERNEL_SRC_URI:pn-linux-intel-iot-lts-6.12    = "git://${TOPDIR}/../managed/linux-intel-iot-lts-6.12;name=machine;branch=HEAD;nobranch=1;protocol=file;usehead=1"
SRCREV_machine:pn-linux-intel-iot-lts-6.12    = "${AUTOREV}"
LINUX_VERSION:pn-linux-intel-iot-lts-6.12     = "6.12+"
KERNEL_CONFIG_URI:pn-linux-intel-iot-lts-6.12 = "git://${TOPDIR}/../managed/yocto-kernel-cache-6.12;type=kmeta;name=meta;protocol=file;destsuffix=${KMETA};branch=HEAD;nobranch=1;usehead=1"
SRCREV_meta:pn-linux-intel-iot-lts-6.12 = "${AUTOREV}"

# Intel lts rt v6.12
KERNEL_SRC_URI:pn-linux-intel-iot-lts-rt-6.12    = "git://${TOPDIR}/../managed/linux-intel-iot-lts-6.12;name=machine;branch=HEAD;nobranch=1;protocol=file;usehead=1"
SRCREV_machine:pn-linux-intel-iot-lts-rt-6.12    = "${AUTOREV}"
LINUX_VERSION:pn-linux-intel-iot-lts-rt-6.12     = "6.12+"
KERNEL_CONFIG_URI:pn-linux-intel-iot-lts-rt-6.12 = "git://${TOPDIR}/../managed/yocto-kernel-cache-6.12;type=kmeta;name=meta;protocol=file;destsuffix=${KMETA};branch=HEAD;nobranch=1;usehead=1"
SRCREV_meta:pn-linux-intel-iot-lts-rt-6.12 = "${AUTOREV}"

# Intel mainline tracking v6.15
KERNEL_SRC_URI:pn-linux-intel-iot-mlt    = "git://${TOPDIR}/../managed/linux-intel-iot-mlt;name=machine;branch=HEAD;nobranch=1;protocol=file;usehead=1"
SRCREV_machine:pn-linux-intel-iot-mlt    = "${AUTOREV}"
LINUX_VERSION:pn-linux-intel-iot-mlt     = "6.15+"
KERNEL_CONFIG_URI:pn-linux-intel-iot-mlt = "git://${TOPDIR}/../managed/yocto-kernel-cache;type=kmeta;name=meta;protocol=file;destsuffix=${KMETA};branch=HEAD;nobranch=1;usehead=1"
SRCREV_meta:pn-linux-intel-iot-mlt = "${AUTOREV}"

####
# SRC_URI, SRC_REV and PV cannot be set through python() without incurring race conditions
# causing do_fetch to fail.

include internal/auto.conf
include auto-${LAYERSERIES_COMPAT_core}.inc
